# Config file for Air
root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o tmp/main ./cmd/api"
  bin = "tmp/main"
  full_bin = "tmp/main"
  include_ext = ["go", "tpl", "html", "tmpl"]
  exclude_dir = ["vendor", "tmp", "scripts"]
  delay = 1000
